### ISSUE TITLE
error with latest version

### ISSUE THREAD

**Issue by naivefun** [William-Yeh/ansible-oracle-java#11]
I ran it on ubuntu 14.04 64, and got these:

failed: [xx.xx.xx.xx] => {"cmd": "/usr/bin/update-alternatives --install /usr/lib/jvm/java java_sdk /usr/java/default 50", "failed": true, "rc": 2}
stderr: update-alternatives: error: error creating symbolic link `/usr/lib/jvm/java.dpkg-tmp': No such file or directory

stdout: update-alternatives: using /usr/java/default to provide /usr/lib/jvm/java (java_sdk) in auto mode

msg: update-alternatives: error: error creating symbolic link `/usr/lib/jvm/java.dpkg-tmp': No such file or directory
...ignoring

**Comment by William-Yeh** [comment]
The alternative link `java_sdk` was introduced for the previous issue: https://github.com/William-Yeh/ansible-oracle-java/issues/3

I haven't come out a better way to handle this case, so this line of task was marked as `ignore_errors`.  Any idea to fix this?

**Comment by ssbarnea** [comment]
Why is this closed? Is my impression or both #11 and #13 are cross linked, and closed as duplicated?

I am facing the same bug on Debian while deploying Java using ansible.
