### ISSUE TITLE
Re-downloading tarball on every install (on same machine)

### ISSUE THREAD

**Issue by sadams** [William-Yeh/ansible-oracle-java#19]
In my test env, I have several services being installed on a single machine.

However, with Ansible 2.0 (maybe earlier too), it is re-downloading the java tarball on each play. I think the culprit is 'check if specific version of Oracle JDK is installed?'. At a guess i would say that the response from check-tarball-installed.sh is being cached between plays because 'changed_when: false' means it will never report a change (and so doesn't re-register the jdk_info in order to skip "install-jdk-tarball.yml"):

https://github.com/William-Yeh/ansible-oracle-java/blob/master/tasks/use-tarball.yml#L12

**Comment by sadams** [comment]
... or it might just that `fetch.yml` has no condition around the download... (the 'creates' wont stop it because it's removed after installation):
https://github.com/William-Yeh/ansible-oracle-java/blob/master/tasks/fetch.yml#L18
followed by:
https://github.com/William-Yeh/ansible-oracle-java/blob/master/tasks/main.yml#L68
before the next run...

**Comment by William-Yeh** [comment]
I refactor the role with Ansible 2.0.

Please check: https://github.com/William-Yeh/ansible-oracle-java/commit/7479eb7c56cc5b7f215e675a8f5afef55a2c4ebe

**Comment by sadams** [comment]
fixes the issue - great, thanks!
