### ISSUE TITLE
jdk 1.7.79 x 64 installation problem/ubuntu x64

### ISSUE THREAD

**Issue by Tirex** [William-Yeh/ansible-oracle-java#25]
Hi.

You need setup user values for jdk_version and other vars if user installed version not listed in set-role-variables.yml.

Fot example i try to install java_version 7 and java_subversion 79  jdk_arch x64 from local file. 

In during installation i got error  'jdk_version' is undefined.

**Comment by William-Yeh** [comment]
Do you want to bypass version checks when the tar.gz/rpm files are on the local?

**Comment by Tirex** [comment]
Yes

**Comment by William-Yeh** [comment]
I've added a new option `jdk_tarball_file` in https://github.com/William-Yeh/ansible-oracle-java/commit/661cc68653750bbb904243570cf9318d0b93a178

Below is extracted from README:

### Customized variables, if absolutely necessary

If you have a pre-downloaded `jdk_tarball_file` whose filename cannot be inferred successfully by `tasks/set-role-variables.yml`, you may specify it explicitly: 

``` yaml
# Specify the pre-fetch filename (without tailing .tar.gz or .rpm or .dmg);
# used in conjunction with `java_download_from_oracle: false`.

jdk_tarball_file

# For example, if you have a `files/jdk-7u79-linux-x64.tar.gz` locally,
# but the filename cannot be inferred successfully by `tasks/set-role-variables.yml`,
# you may specify the following variables in your playbook:
#
#    java_version:    7
#    java_subversion: 79
#    java_download_from_oracle: false
#    jdk_tarball_file: jdk-7u79-linux-x64
#
```
