### ISSUE TITLE
Need java_sdk alternative slave

### ISSUE THREAD

**Issue by hvisage** [William-Yeh/ansible-oracle-java#3]
Too busy to do the fork/pull request thingy y ;( )

Needs to modify the files/update-alternatives.sh to be modified to include `--slave   /usr/lib/jvm/java java_sdk /usr/java/default`

```
    update-alternatives --verbose  \
        --install /usr/bin/java   java   /usr/java/default/bin/java 1  \
        --slave   /usr/bin/javac  javac  /usr/java/default/bin/javac   \
        --slave   /usr/bin/jar    jar    /usr/java/default/bin/jar \
        --slave   /usr/lib/jvm/java java_sdk /usr/java/default
```

**Comment by William-Yeh** [comment]
Hi @hvisage 

May I ask what if this line is missing?

**Comment by hvisage** [comment]
The line:
   --slave   /usr/lib/jvm/java java_sdk /usr/java/default
is missing, yes.

If this is missing, then (At least on Centos 7.1) the default Maven then uses Javac from openjdk-1.7, and fails on some stuff where the developers need/specify 1.8

> On 22 Sep 2015, at 9:03 AM, William Yeh notifications@github.com wrote:
> 
> Hi @hvisage https://github.com/hvisage
> May I ask what if this line is missing?
> 
> —
> Reply to this email directly or view it on GitHub https://github.com/William-Yeh/ansible-oracle-java/issues/3#issuecomment-142198397.

---

Hendrik Visage
Envisage Systems / Envisage Cloud Solutions
084-612-5345 or 083-675-5506
hvisage@envisage.co.za mailto:hvisage@envisage.co.za
