### ISSUE TITLE
Install JDK7 and 8 in one playbook

### ISSUE THREAD

**Issue by tao-zhang** [William-Yeh/ansible-oracle-java#36]
```
- { role: williamyeh.oracle-java,
    java_version: 7,
    java_subversion: 80,
    java_set_javahome: true,
    java_install_jce: true }

- { role: williamyeh.oracle-java,
    java_version: 8,
    java_subversion: 92,
    java_install_jce: true }
```

For the second role, the error part is:

TASK [williamyeh.oracle-java : compose filename, if necessary] *****************
task path: /etc/ansible/roles/williamyeh.oracle-java/tasks/set-role-variables.yml:111
skipping: [127.0.0.1] => {"changed": false, "skip_reason": "Conditional check failed", "skipped": true}

TASK [williamyeh.oracle-java : compose url for downloading file, if necessary] *
task path: /etc/ansible/roles/williamyeh.oracle-java/tasks/set-role-variables.yml:116
ok: [127.0.0.1] => {"ansible_facts": {"jdk_tarball_url": "http://download.oracle.com/otn-pub/java/jdk/**8u92-b14**/**jdk-7u80-linux-x64**"}, "changed": false}

It looks **jdk_tarball_file** is not cleared after first role execution. The second role finds **jdk_tarball_file** still exists.

**Comment by William-Yeh** [comment]
This role doesn't consider the situation that two or more JDK/JRE versions co-exist within the same managed node. In fact, I'm also against such use case, even for non-Java runtime such as rvm (for Ruby), virtualenv (for Python), and nvm (for Node.js).

In my opinion, Docker is more appropriate for such a requirement.
