### ISSUE TITLE
"'jdk_version' is undefined" on CentOS 7

### ISSUE THREAD

**Issue by naivefun** [William-Yeh/ansible-oracle-java#37]
> TASK [williamyeh.oracle-java : check if specific version of Oracle JDK is installed?] ***
> fatal: [xxxxx]: FAILED! => {"failed": true, "msg": "'jdk_version' is undefined"}
> fatal: [xxxx]: FAILED! => {"failed": true, "msg": "'jdk_version' is undefined"}
>         to retry, use: --limit @install.retry

When I add `java_subversion`

**Comment by William-Yeh** [comment]
Sorry but I cannot reproduce your issue.

My test:
https://asciinema.org/a/49901
