### ISSUE TITLE
Fetch'-ing on Darwin retrieves .tar.gz instead of .dmg

### ISSUE THREAD

**Issue by wvanmourik** [William-Yeh/ansible-oracle-java#46]
Typo in: missing ( ) to combine the check.
- name: get JDK tarball (as tar.gz file)

Change:
when: ansible_pkg_mgr != "yum" or ansible_pkg_mgr != "zypper" and ansible_os_family != 'Darwin'

Into:
when: (ansible_pkg_mgr != "yum" or ansible_pkg_mgr != "zypper") and ansible_os_family != 'Darwin'

**Comment by mmannerm** [comment]
See PR #39 . It has been there for ages now with no sign of actually being accepted.
