### ISSUE TITLE
How can I config to specific jdk 8?

### ISSUE THREAD

**Issue by ipeisong** [William-Yeh/ansible-oracle-java#5]
Right now there are some bugs in latest 8u60 JDK, we need 8u46, so how can I config to do that? 
I'm using ubuntu.
Thanks.

**Comment by William-Yeh** [comment]
According to “WebUpd8” team's list [Packages in “Oracle Java (JDK) 7 / 8 / 9 Installer PPA”](https://launchpad.net/~webupd8team/+archive/ubuntu/java/+packages), not all 8uXX JDK are available for Ubuntu Trusty.

If pinning is absolutely necessary for Ubuntu/Debian distributions, maybe we should try to download specific tarballs directly from Oracle.

Any comment?

**Comment by ipeisong** [comment]
Sorry, how about 8u45? I just don't know how to config, thanks.

**Comment by William-Yeh** [comment]
As mentioned in the list, currently 8u45 is only available for Utopic and Lucid.

**Comment by ipeisong** [comment]
Ok, let's say I am using Lucid, is it possible to config this role to use 8u45?
Or do you mean because of lacking support for Trusty, we cannot do that?

**Comment by William-Yeh** [comment]
I have some ideas to generalize these version issues.  But I've been attending Velocity NY 2015 these days. So I'll work on this when I come back.

**Comment by ipeisong** [comment]
Thanks! Looking forward

**Comment by William-Yeh** [comment]
Beginning from https://github.com/William-Yeh/ansible-oracle-java/commit/855e804d84ef8bbbc3e03684cbcd9ee417d79d9d you may override JDK version as follows.

**8u60**:

``` yaml
java_version: 8
java_subversion: 60
```

**8u51**:

``` yaml
java_version: 8
java_subversion: 51
```

**8u45**:

``` yaml
java_version: 8
java_subversion: 45
```

You may also modify the `tasks/set-role-variables.yml` file, if necessary.
