### ISSUE TITLE
Cannot install JDK8 and Centos 6.7

### ISSUE THREAD

**Issue by wawrzek** [William-Yeh/ansible-oracle-java#7]
To install JDK 8 on CentOS 6.7 I have to modify following condition:
    `when: java_version == 8  and  (jdk8_info.stdout|from_json).not_found`
to 
    `when: java_version == 8`

When I look at `jdk8_info.stdout` I see:
 `"msg": "{'stdout': '{ \"found\": true  , \"not_found\": false }`

I run playbook from

> ansible --version
> ansible 1.9.2
> at  Ubuntu 15.04

**Comment by William-Yeh** [comment]
You're using an older version of this role.

Pick a newer version, and try again.

**Comment by wawrzek** [comment]
That's right. I wonder how I got that older version. Anyway, all is good now. Thanks for sharing this project.
