### ISSUE TITLE
Ansible java role issue

### ISSUE THREAD

**Issue by hrstoyanov** [William-Yeh/ansible-oracle-java#8]
William,
The "williamyeh.oracle-java" role leaves a copy of the downloaded jdk and fails to delete it after installation. I use your debian8 image as a base. Here is what my container looks like after using the role - notice the downloaded jdk bundle:

```
total 177020
     4 -rw-rw-r-- 1 root root       396 Oct 23 04:16 Dockerfile
     4 -rwxr-xr-x 1 root root       397 Oct 23 04:17 check-tarball-installed.sh
     4 -rw-rw-r-- 1 root root       381 Oct 23 04:16 docker-image-base.yml
     4 drwxrwxr-x 2 root root      4096 Oct 23 04:16 group_vars
176996 -rw-r--r-- 1 root root 181238643 Oct 23 04:18 jdk-8u60-linux-x64.tar.gz
     4 drwxrwxr-x 2 root root      4096 Oct 23 04:16 roles
     4 drwxrwxr-x 2 root root      4096 Oct 23 04:16 templates

```

**Comment by William-Yeh** [comment]
Yes, I'll provide an option to clean up tarballs and rpm files in the next revision.

**Comment by hrstoyanov** [comment]
Thank you.

/Hristo Stoyanov

**Comment by William-Yeh** [comment]
Done. 

Since 1.1.3 https://github.com/William-Yeh/ansible-oracle-java/tree/1.1.3

**Comment by hrstoyanov** [comment]
Thank you.

/Hristo Stoyanov
